### ISSUE TITLE
Align: Implement aligning color images similarly

### ISSUE THREAD

**Issue by braymp** [CellProfiler/centrosome#43]
_From @braymp on October 9, 2015 16:40_

The Align module can align two grayscale images w.r.t each other, but yields an error if a color is used for alignment, This is reasonable since alignment of color images is a trickier thing, but if I want to align a color image with the "Similarly" option, it should be straightforward to do: simply apply the same offset to all 3 channels.

_Copied from original issue: CellProfiler/CellProfiler#1634_

**Comment by LeeKamentsky** [comment]
none of the code is in centrosome
