### ISSUE TITLE
HTML Documentation in rtd 

### ISSUE THREAD

**Issue by chsasank** [CellProfiler/centrosome#55]
Hi,

I just stumbled up on this library when I was going through cell profiler code to use its routines for one of my projects.
It's awesome that cell profiler's backend is separated in to a library.

I think this library has a lot of potential to be _the_ cell related image processing library and one of the things that's missing is proper documentation.
Although code itself is very well documented, to attract the attention of developers there should be a sphinx built documentation hosted somewhere.

So I propose us to write some great restructedtext documents and host them on https://readthedocs.org.
What do you people think? I'm willing to contribute if the community is willing to collaborate.

Sasank.

**Comment by AnneCarpenter** [comment]
This was a great idea, but actually our aim is for most image processing code to end up in scikit-image rather than residing in centrosome forever.
