### ISSUE TITLE
ImportError: No module named Cython.Build

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/centrosome#78]
Unable to `pip install centrosome`:

```
$ pip install centrosome
Collecting centrosome
  Downloading centrosome-1.0.8.tar.gz (570kB)
    100% |████████████████████████████████| 573kB 4.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_v/wzmwy8dx6rz9hp0y53d8dg69bglyll/T/pip-build-Q7hyv0/centrosome/setup.py", line 1, in <module>
        import Cython.Build
    ImportError: No module named Cython.Build
```

**Comment by lechatthecat** [comment]
Maybe try 
pip install --upgrade cython

**Comment by ashishgupta1350** [comment]
pip install --upgrade cython will not work. Is there something else to try? I am facing the same issue.

**Comment by lechatthecat** [comment]
You already have cython module? 
What version of python do you use?

**Comment by ashishgupta1350** [comment]
I am using Python 3.6 currently. I also upgraded Cython to the latest version.

**Comment by lechatthecat** [comment]
Are you using pyenv/virutalenv?
Are you sure you have the latest python for python3.6?
Try:
$ python3.6 -m pip install --upgrade cython
And
$ sudo python3.6 -m pip install --upgrade cython

**Comment by ShettyHarapanahalli** [comment]
I am trying to install mscoco, i get the below error, can not get whats the problem - 
  
`$ sudo python setup.py build_ext --inplace
  Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build`

I did install centrosome-1.0.9 and cython-0.28.5 `already`

**Comment by haniomar** [comment]
I got the same problem, even i work by python 3.6.5
but i tried this
python3  setup.py install
and it worked well

**Comment by danFromTelAviv** [comment]
inspired by ShettyHarapanahalli I just added sudo and that worked for me. Not sure why it failed for him/her.

**Comment by csjunxu** [comment]
I use python setup.py install without sudo, it works. With sudo, still fails.

**Comment by jazzina** [comment]
try to upgrade pip. It`s worked for me

**Comment by mungsoo** [comment]
> Maybe try
> pip install --upgrade cython

You made my day!! Thank you so much

**Comment by bhaveshpadharia** [comment]
pip install --upgrade cython

**Comment by omarish** [comment]
`pip install --upgrade cython` worked for me on 3.7.2.

**Comment by samhithaaaa** [comment]
> Maybe try
> pip install --upgrade cython

yes,this works ,thank you

**Comment by anerisheth19** [comment]
While setting up pycocotools, the python setup failed and showed the ImportError: No module named Cython.Build.

If you're using python 2.7 or above, type on terminal: pip install --upgrade cython
This should work. The error is probably because the cython version installed from pip is incompatible to the python version on your system. 

Thanks

**Comment by ali1366** [comment]
This solves my problem:
`python -m pip install --upgrade pip`
then:
`pip install --upgrade cython`

**Comment by MISSIVA20** [comment]
> I am trying to install mscoco, i get the below error, can not get whats the problem -
> 
> `$ sudo python setup.py build_ext --inplace Traceback (most recent call last): File "setup.py", line 2, in <module> from Cython.Build import cythonize ImportError: No module named Cython.Build`
> 
> I did install centrosome-1.0.9 and cython-0.28.5 `already`

i have same error do you found a solution??

**Comment by anerisheth19** [comment]
> > I am trying to install mscoco, i get the below error, can not get whats the problem -
> > `$ sudo python setup.py build_ext --inplace Traceback (most recent call last): File "setup.py", line 2, in <module> from Cython.Build import cythonize ImportError: No module named Cython.Build`
> > I did install centrosome-1.0.9 and cython-0.28.5 `already`
> 
> i have same error do you found a solution??

Check previous comments. It should solve it.

**Comment by MISSIVA20** [comment]
> pip install --upgrade cython ne fonctionnera pas. Y a-t-il autre chose à essayer? Je suis confronté au même problème.

vous avez résolu le problème j'ai la même erreur

**Comment by MISSIVA20** [comment]
> Cela résout mon problème:
> `python -m pip install --upgrade pip`
> alors:
> `pip install --upgrade cython`

dans quel répertoire vous avez exécuter ces cmd j'ai la même problème malgré que j'ai passé par ces deux cmd

**Comment by Lina0125** [comment]
You can check your pip list like this:
sudo pip list
if Cython doesn't appear at list,you should install it with sudo:
sudo pip install cython

**Comment by Prakashthakur0021** [comment]
> I am trying to install mscoco, i get the below error, can not get whats the problem -
> 
> `$ sudo python setup.py build_ext --inplace Traceback (most recent call last): File "setup.py", line 2, in <module> from Cython.Build import cythonize ImportError: No module named Cython.Build`
> 
> I did install centrosome-1.0.9 and cython-0.28.5 `already`

I am getting same problem🤦‍♂️😢

**Comment by NoCtrlZ** [comment]
I am using python3 and the following command works for me.
```
$ pip3 install --user cython
```

**Comment by nasimuddin01** [comment]
> I use python setup.py install without sudo, it works. With sudo, still fails.

This solved my issue...

**Comment by nikitamalviya** [comment]
pip install Cython

**Comment by f22j** [comment]
On VS Code, i changed the python interpreter to the one in the  virtualenv folder The error was fixed.

**Comment by f22j** [comment]
On VS Code, after pip install Cython, i changed the python interpreter to the one inside the virtualenv folder. The error was fixed.

**Comment by abbottsteve** [comment]
Below worked in my case

 **python3 setup.py build_ext --inplace**

**Comment by willrnch** [comment]
With conda:

```
conda install -c anaconda cython
```

Ref: https://anaconda.org/anaconda/cython
